#!/usr/bin/env python3

import argparse

def parse_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument("-i", dest="input", type=str, help="Input file")
    return parser.parse_args()

args = parse_arguments()
